version: "3"

services:
  db:
    hostname: "db"
    build: "./src/DB/"
    environment:
      - ACCEPT_EULA=true
      - SA_PASSWORD=qweQWE123
  quartz_worker:
    build:
      context: "."
      dockerfile: "QuartzWorker.Dockerfile"